#[150397532] Add travis 150397532
andela/elrond-cfh pull request #4
Opened 2017-08-22 14:50 UTC by THEozmic

#### What does this PR do?
Adds Travis and coveralls badges and config
#### Description of Task to be completed?

2017-08-22 14:51 UTC, THEozmic commented
I'm merging this commit regardless of the travis result, since travis is the commit. :)

2017-08-22 15:32 UTC, mradeybee requested changes
Remove the `.env` file and add it to your git ignore file. 

Also, add at least one test to make sure that Travis runs successfully.

2017-08-22 15:32 UTC, mradeybee commented on .env
> +MONGOHQ_URL=mongodb://localhost:20217/cfh
Please add this file to your gitignore, you should **NEVER** push sensitive files like this to git.

2017-08-22 15:33 UTC, mradeybee commented
Probably you need to wait for @ayeniblessing101's task to be merged.

2017-08-22 15:46 UTC, johadi reviewed
I also suggest that travis repo_token should be included in the .env file. I see it as a very sensitive data 
`webhooks: https://coveralls.io/webhook?repo_token=AlQ0K4WyO8yno9TSEP9t3SoyrkmoYgI8I`

2017-08-22 15:46 UTC, johadi10 commented on travis.yml
> +  webhooks: https://coveralls.io/webhook?repo_token=AlQ0K4WyO8yno9TSEP9t3SoyrkmoYgI8I
I suggest this repo_token should also be included in .env file as it is also a sensitive data

2017-08-22 17:40 UTC, mradeybee requested changes
Set all env variables on travis and not in the code. See how here. https://docs.travis-ci.com/user/environment-variables/

2017-08-23 11:19 UTC, mradeybee approved these changes
GTM

2017-08-23 11:21 UTC, merged