[Chore #150397534] setup unit testing for frontend
andela/elrond-cfh pull request #5
Opened 2017-08-22 15:05 UTC by ayeniblessing101

#### What does this PR do?
Setup unit testing for the frontend

#### Description of Task to be completed?
- Installed karma, jasmine-core, karma-jasmine,
 karma-chrome-launcher

#### How should this be manually tested?
- Run karma start

#### Any background context you want to provide?
N/A

#### What are the relevant pivotal tracker stories?
setup unit testing for the frontend #150397534

#### Screenshots (if appropriate)
N/A

#### Questions:
N/A

2017-08-22 15:06 UTC, THEozmic commented on test/index.spec.js
> +  })
Please fix this. Thanks

2017-08-22 15:29 UTC, mradeybee requested changes
@ayeniblessing101 This looks okay. I will suggest you add a template of what the test should look like so it will be easier for the next person to write a test to do so. 

Also, in your `karma.config.js` file, make sure the space between the lines are reduced to one. You can ignore if it is an auto-generated file.

2017-08-22 15:29 UTC, mradeybee commented on karma.conf.js
> +
Remove extra space here.

2017-08-22 15:29 UTC, mradeybee commented on karma.conf.js
> +
Ditto extra space.

2017-08-22 15:29 UTC, mradeybee commented on karma.conf.js
> +  })
Always listen to hound CI!

2017-08-23 10:57 UTC, mradeybee approved these changes
GTM

2017-08-23 11:13 UTC, merged