Ch deploy base app 150397527
andela/elrond-cfh pull request #6
Opened 2017-08-22 21:03 UTC by QUDUSKUNLE

What does this PR do?

I ensured this run on local machine before I deploy.

2017-08-23 10:02 UTC, johadi approved these changes

2017-08-24 09:54 UTC, johadi approved these changes
GTM

2017-08-25 05:33 UTC, mradeybee requested changes
@QUDUSKUNLE change the places where you have `var` to `let` ALWAYS listen to hound ci

2017-08-29 07:47 UTC, mradeybee requested changes
@QUDUSKUNLE I think you should close this PR since you don't need it anymore.

2017-08-31 14:23 UTC, closed without merging